linters-settings:
  gosimple:
    go: "1.17"
    checks: [
      "all", 
      "-ST1000", 
      "-ST1003", 
      "-ST1016", 
      "-ST1020", 
      "-ST1021", 
      "-ST1022",
      "-ST1005",
      "-SA1006",
      "-SA4006",
      "-SA6005",
      "-SA4011",
      "-ST1011",
    ]